[server]
port = 5000
addr = "0.0.0.0"

[database]
# path for sqlite databases
mainDB = "./database.db"
sessionsDB = "./sessions.db"

[management]
noSignup = false  # disables user signup if true
rateLimitMax = 20 # Maximum of 20 requests in 30 seconds

[admin]
# admin pages route. can be any string starts with `/`.
# but it's better to set a randomly generated string
# with ONLY letters and numbers.
route = "/sX4MGykDZq"
