DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER PRIMARY KEY,
    -- target TEXT UNIQUE NOT NULL,
    target VARCHAR(256) NOT NULL,
    -- hash VARCHAR(64) UNIQUE NOT NULL,
    hash VARCHAR(10) UNIQUE NOT NULL,
    clicked INTEGER DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
