version: "3.7"

services:
  app:
    image: cutlink:latest
    container_name: dockerCutlink1
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - $PWD/config.toml:/etc/cutlink/config.toml

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/nginx/ssl:/ssl
    ports:
      - 8443:443
